POST http://localhost:5000/tibber-developer-test/enter-path HTTP/1.1
content-type: application/json

{
    "start": {
        "x": -55510,
        "y": 88888822
    },
    "commands": [
        {
            "direction": "east",
            "steps": -2
        },
        {
            "direction": "north",
            "steps": 1
        }
    ]
}