POST https://localhost:7287/tibber-developer-test/enter-path HTTP/1.1
content-type: application/json

{
    "start": {
        "x": 10,
        "y": 22
    },
    "commands": [
        {
            "direction": "east",
            "steps": 2
        },
        {
            "direction": "north",
            "steps": 1
        }
    ]
}